// events from file arm/armv7-common/events
    {0x00, CTR1 | CTR2 | CTR3 | CTR4 | CTR5 | CTR6, "PMNC_SW_INCR",
     "Software increment of PMNC registers"},
    {0x01, CTR1 | CTR2 | CTR3 | CTR4 | CTR5 | CTR6, "IFETCH_MISS",
     "Instruction fetch misses from cache or normal cacheable memory"},
    {0x02, CTR1 | CTR2 | CTR3 | CTR4 | CTR5 | CTR6, "ITLB_MISS",
     "Instruction fetch misses from TLB"},
    {0x03, CTR1 | CTR2 | CTR3 | CTR4 | CTR5 | CTR6, "DCACHE_REFILL",
     "Data R/W operation that causes a refill from cache or normal cacheable memory"},
    {0x04, CTR1 | CTR2 | CTR3 | CTR4 | CTR5 | CTR6, "DCACHE_ACCESS",
     "Data R/W from cache"},
    {0x05, CTR1 | CTR2 | CTR3 | CTR4 | CTR5 | CTR6, "DTLB_REFILL",
     "Data R/W that causes a TLB refill"},
    {0x06, CTR1 | CTR2 | CTR3 | CTR4 | CTR5 | CTR6, "DREAD",
     "Data read architecturally executed (note: architecturally executed = for instructions that are unconditional or that pass the condition code)"},
    {0x07, CTR1 | CTR2 | CTR3 | CTR4 | CTR5 | CTR6, "DWRITE",
     "Data write architecturally executed"},
    {0x08, CTR1 | CTR2 | CTR3 | CTR4 | CTR5 | CTR6, "INSTR_EXECUTED",
     "All executed instructions"},
    {0x09, CTR1 | CTR2 | CTR3 | CTR4 | CTR5 | CTR6, "EXC_TAKEN",
     "Exception taken"},
    {0x0A, CTR1 | CTR2 | CTR3 | CTR4 | CTR5 | CTR6, "EXC_EXECUTED",
     "Exception return architecturally executed"},
    {0x0B, CTR1 | CTR2 | CTR3 | CTR4 | CTR5 | CTR6, "CID_WRITE",
     "Instruction that writes to the Context ID Register architecturally executed"},
    {0x0C, CTR1 | CTR2 | CTR3 | CTR4 | CTR5 | CTR6, "PC_WRITE",
     "SW change of PC, architecturally executed (not by exceptions)"},
    {0x0D, CTR1 | CTR2 | CTR3 | CTR4 | CTR5 | CTR6, "PC_IMM_BRANCH",
     "Immediate branch instruction executed (taken or not)"},
    {0x0E, CTR1 | CTR2 | CTR3 | CTR4 | CTR5 | CTR6, "PC_PROC_RETURN",
     "Procedure return architecturally executed (not by exceptions)"},
    {0x0F, CTR1 | CTR2 | CTR3 | CTR4 | CTR5 | CTR6, "UNALIGNED_ACCESS",
     "Unaligned access architecturally executed"},
    {0x10, CTR1 | CTR2 | CTR3 | CTR4 | CTR5 | CTR6, "PC_BRANCH_MIS_PRED",
     "Branch mispredicted or not predicted. Counts pipeline flushes because of misprediction"},
    {0x12, CTR1 | CTR2 | CTR3 | CTR4 | CTR5 | CTR6, "PC_BRANCH_MIS_USED",
     "Branch or change in program flow that could have been predicted"},
    {0xFF, CTR0, "CPU_CYCLES",
     "Number of CPU cycles"},
